CREATE TABLE IF NOT EXISTS `Usuario`(
`CODUSUARIO` Int(11) NOT NULL AUTO_INCREMENT,
`LOGIN` Varchar(20) DEFAULT NULL,
`SENHA` Varchar(20) DEFAULT NULL,
`NOME` Varchar(50) DEFAULT NULL,
`TELEFONE` Int(11) DEFAULT NULL,
`EMAIL` Varchar(50) DEFAULT NULL,
PRIMARY KEY (`CODUSUARIO`) );

CREATE TABLE IF NOT EXISTS `Equipamento`(
`CODEQUIPAMENTO` Int(11) NOT NULL AUTO_INCREMENT,
`CODUSUARIO` Int(11) DEFAULT NULL,
`NOME` Varchar(50) DEFAULT NULL,
`DESCRICAO` Varchar(50) DEFAULT NULL,
`OBSEQUIPAMENTO` Varchar(50) DEFAULT NULL,
`QUANTIDADE` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODEQUIPAMENTO`) );

CREATE TABLE IF NOT EXISTS `Ingrediente`(
`CODINGREDIENTE` Int(11) NOT NULL AUTO_INCREMENT,
`CODUSUARIO` Int(11) DEFAULT NULL,
`NOME` Varchar(50) DEFAULT NULL,
`QUANTIDADE` Float(7,2) DEFAULT NULL,
`DATAFAB` datetime DEFAULT NULL,
`DATAVENC` datetime DEFAULT NULL,
`VALOR` Float(7,2) DEFAULT NULL,
`DATAENTRADA` datetime DEFAULT NULL,
`DATASAIDA` datetime DEFAULT NULL,
`OBS` Varchar(200) DEFAULT NULL,
PRIMARY KEY (`CODINGREDIENTE`) );

CREATE TABLE IF NOT EXISTS `IngredientePrincipal`(
`CODINGREDIENTEPRINCIPAL` Int(11) NOT NULL AUTO_INCREMENT,
`CODINGREDIENTE` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODINGREDIENTEPRINCIPAL`) );

CREATE TABLE IF NOT EXISTS `Malte`(
`CODMALTE` Int(11) NOT NULL AUTO_INCREMENT,
`CODINGREDIENTEPRINCIPAL` Int(11) DEFAULT NULL,
`EBC` Varchar(200) DEFAULT NULL,
PRIMARY KEY (`CODMALTE`) );

CREATE TABLE IF NOT EXISTS `Lupulo`(
`CODLUPULO` Int(11) NOT NULL AUTO_INCREMENT,
`CODINGREDIENTEPRINCIPAL` Int(11) DEFAULT NULL,
`ALFAACIDO` Varchar(30) DEFAULT NULL,
`TIPOLUPULO` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODLUPULO`) );

CREATE TABLE IF NOT EXISTS `Fermento`(
`CODFERMENTO` Int(11) NOT NULL AUTO_INCREMENT,
`CODINGREDIENTEPRINCIPAL` Int(11) DEFAULT NULL,
`TIPOFERMENTO` Int(11) DEFAULT NULL,
`ESTILOFERMENTO` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODFERMENTO`) );

CREATE TABLE IF NOT EXISTS `IngredienteAdendo`(
`CODINGREDIENTEADENDO` Int(11) NOT NULL AUTO_INCREMENT,
`CODINGREDIENTE` Int(11) DEFAULT NULL,
`USO` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODINGREDIENTEADENDO`) );

CREATE TABLE IF NOT EXISTS `IngredienteUsado`(
`CODINGREDIENTEUSADO` Int(11) NOT NULL AUTO_INCREMENT,
`CODINGREDIENTE` Int(11) DEFAULT NULL,
`QTD_USADO` float DEFAULT NULL,
`TIPOUSADO` Varchar(50) DEFAULT NULL,
`TEMPOUSADO` Int(11) DEFAULT NULL,
`TIPOINGREDIENTE` Varchar(50) DEFAULT NULL,
PRIMARY KEY (`CODINGREDIENTEUSADO`) );

CREATE TABLE IF NOT EXISTS `Brassagem`(
`CODBRASSAGEM` Int(11) NOT NULL AUTO_INCREMENT,
`CODUSUARIO` Int(11) DEFAULT NULL,
`CODRECEITA` Int(11) DEFAULT NULL,
`DATAINICIAL` datetime DEFAULT NULL,
`DATAFINAL` datetime DEFAULT NULL,
`OBS` Varchar(200) DEFAULT NULL,
`STATUSBRASSAGEM` Varchar(2) DEFAULT NULL,
PRIMARY KEY (`CODBRASSAGEM`) );

CREATE TABLE IF NOT EXISTS `Receita`(
`CODRECEITA` Int(11) NOT NULL AUTO_INCREMENT,
`CODUSUARIO` Int(11) DEFAULT NULL,
`NOME` Varchar(50) DEFAULT NULL,
`DECRICAO` Varchar(200) DEFAULT NULL,
`ESTILO` Varchar(50) DEFAULT NULL,
`TIPOBRASSAGEM` Int(11) DEFAULT NULL,
`TIPORECEITA` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODRECEITA`) );

CREATE TABLE IF NOT EXISTS `Mostura`(
`CODMOSTURA` Int(11) NOT NULL AUTO_INCREMENT,
`CODRECEITA` Int(11) DEFAULT NULL,
`CTD_AGUAMOSTURA` Int(11) DEFAULT NULL,
`QUANTIDADEAGUALAVAGEM` Int(11) DEFAULT NULL,
`SG_RECEITA` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODMOSTURA`) );

CREATE TABLE IF NOT EXISTS `RampaMostura`(
`CODRAMPAMOSTURA` Int(11) NOT NULL AUTO_INCREMENT,
`CODMOSTURA` Int(11) DEFAULT NULL,
`NOME` Varchar(50) DEFAULT NULL,
`TEMPO` Int(11) DEFAULT NULL,
`TEMPERATURA` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODRAMPAMOSTURA`) );

CREATE TABLE IF NOT EXISTS `Fervura`(
`CODFERVURA` Int(11) NOT NULL AUTO_INCREMENT,
`CODRECEITA` Int(11) DEFAULT NULL,
`TEMPOFERVURA` Int(11) DEFAULT NULL,
`OG_RECEITA` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODFERVURA`) );

CREATE TABLE IF NOT EXISTS `Fermentacao`(
`CODFERMENTACAO` Int(11) NOT NULL AUTO_INCREMENT,
`CODRECEITA` Int(11) DEFAULT NULL,
`FGDARECEITA` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODFERMENTACAO`) );

CREATE TABLE IF NOT EXISTS `RampaFermentacao`(
`CODFERMENTACAO` Int(11) NOT NULL AUTO_INCREMENT,
`NOME` Varchar(50) DEFAULT NULL,
`TEMPO` Int(11) DEFAULT NULL,
`TEMPERATURA` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODFERMENTACAO`) );

CREATE TABLE IF NOT EXISTS `Maturacao`(
`CODMATURACAO` Int(11) NOT NULL AUTO_INCREMENT,
`CODRECEITA` Int(11) DEFAULT NULL,
PRIMARY KEY (`CODMATURACAO`) );

CREATE TABLE IF NOT EXISTS `RampaMaturacao`(
`CODRAMPAMATURACAO` Int(11) NOT NULL AUTO_INCREMENT,
`CODMATURACAO` Int(11) DEFAULT NULL,
`NOME` Varchar(50) DEFAULT NULL,
`TEMPO` Int(11) DEFAULT NULL,
`TEMPERATURA` Int(20 ) DEFAULT NULL,
PRIMARY KEY (`CODRAMPAMATURACAO`) );
